### PR TITLE
Fixed ALSA capture device monitoring.

### LINKED ISSUE #241: [Enhancement] Allow monitoring volume and mute status of audio input devices
At the moment it looks like it is only possible to monitor audio output devices. (At least for me any attempts to add an ALSA capture device or PulseAudio source failed)

 It would be great if it would also be possible to monitor input devices.

### PR DESCRIPTION
**Pull request by jdevelop**
When using ALSA, the "Capture" mixer doesn't have the playback channel,
instead "capture"-related methods should be used to get information
about the current volume / state of the mixer.

Fixes #241

### CODE REVIEW

File: src/print_volume.c [hunk 1]
```diff
@@ -165,12 +165,22 @@ void print_volume(yajl_gen json_gen, char *buffer, const char *fmt, const char *
 
     /* Get the volume range to convert the volume later */
     snd_mixer_handle_events(m);
-    err = snd_mixer_selem_get_playback_dB_range(elem, &min, &max) ||
-          snd_mixer_selem_get_playback_dB(elem, 0, &val);
-    if (err != 0 || min >= max) {
-        err = snd_mixer_selem_get_playback_volume_range(elem, &min, &max) ||
-              snd_mixer_selem_get_playback_volume(elem, 0, &val);
-        force_linear = true;
+    if (!strncasecmp(mixer, "capture", strlen("capture"))) {
```
Comment (Airblader) [inline src/print_volume.c]: Since these two blocks are identical apart from the called functions, I think we should introduce a macro here that we then call in each branch with the appropriate functions passed in

File: src/print_volume.c [hunk 2]
```diff
@@ -201,6 +211,13 @@ void print_volume(yajl_gen json_gen, char *buffer, const char *fmt, const char *
             START_COLOR("color_degraded");
             fmt = fmt_muted;
         }
+    } else if (snd_mixer_selem_has_capture_switch(elem)) {
```
Comment (Airblader) [inline src/print_volume.c]: Same here

File: include/i3status.h [hunk 3]
```diff
@@ -174,6 +174,23 @@ extern char *pct_mark;
...
+          snd_mixer_selem_get_##channel##_dB(elem, 0, &val);                    \
+    if (err != 0 || min >= max) {                                               \
+        err = snd_mixer_selem_get_##channel##_volume_range(elem, &min, &max) || \
+              snd_mixer_selem_get_##channel##_volume(elem, 0, &val);            \
+        force_linear = true;                                                    \
+    }
+
+#define ALSA_MUTE_SWITCH(channel)                                                       \
+    if ((err = snd_mixer_selem_get_##channel##_switch(elem, 0, &pbval)) < 0)            \
+        fprintf(stderr, "i3status: ALSA: ##channel##_switch: %s\n", snd_strerror(err)); \
```
Comment (orestisf1993) [inline include/i3status.h]:
```suggestion
        fprintf(stderr, "i3status: ALSA: " #channel "_switch: %s\n", snd_strerror(err)); \
```

Comment (jdevelop) [reply include/i3status.h]: Updated, pls have a look.

**Comment by jdevelop** [comment]
Any chance to get it merged into upstream, @Airblader ?

**Comment by Airblader** [comment]
I wasn't aware you had made the changes since there's no notifications for pushes. Please always make sure to drop a comment so we get notified. :-) Thanks for your contribution!

**Comment by qguv** [comment]
@jdevelop: Could you give an example of a working i3status configuration that can make use of this? I'm running Pulse and would like to show whether my microphone is muted—is that possible using this change? Or is additional pulse support necessary?

**Comment by jdevelop** [comment]
@qguv 
```
# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        output_format = "i3bar"
        colors = true
        interval = 5
}

order += "cpu_usage"
order += "load"
order += "volume master"
order += "volume capture"
order += "disk /"
order += "wireless _first_"
order += "ethernet _first_"
order += "battery 0"
order += "tztime zp"
order += "tztime local"

wireless _first_ {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}

ethernet _first_ {
        # if you use %speed, i3status requires root privileges
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

battery 0 {
        format = "%status %percentage %remaining"
}

cpu_usage {
    format = "%usage "
}

tztime local {
        format = "%Y-%m-%d %H:%M"
}

load {
        format = "%1min"
}

disk "/" {
        format = "/ %avail"
}

volume master {
        format = ": %volume"
        format_muted = ""
        device = "hw:0"
        mixer  = "Master"
        mixer_idx = 0
}

volume capture {
        format = ": %volume"
        format_muted = ""
        device = "hw:0"
        mixer  = "Capture"
        mixer_idx = 0
}
```
