### PR TITLE
Read /proc/mounts if /etc/mtab can't be read

### LINKED ISSUE #257: i3status fails to run on WSL w/o /etc/mtab
Since WSL does not currently populate the /etc/mtab file, you must add a dummy file to boot a recent i3status process. This was tested with `i3status 2.11 (2017-01-21) © 2008 Michael Stapelberg and contributors` on Windows 10 (17063).

Running it with strace quickly spotted an ENOENT error right before the segfault. Adding an empty mtab seems to avoid the segfault for now but it might be better to handle cases where we're unable to read this file for one reason or another.

### PR DESCRIPTION
**Pull request by eplanet**
This would fix #257

### CODE REVIEW

File: src/print_disk_info.c [hunk 1]
```diff
@@ -145,15 +145,19 @@ void print_disk_info(yajl_gen json_gen, char *buffer, const char *path, const ch
         if (strlen(sanitized) > 1 && sanitized[strlen(sanitized) - 1] == '/')
             sanitized[strlen(sanitized) - 1] = '\0';
         FILE *mntentfile = setmntent("/etc/mtab", "r");
-        struct mntent *m;
+        if (mntentfile == NULL) {
```
Comment (orestisf1993) [inline src/print_disk_info.c]:
```suggestion
        if (mntentfile == NULL) {
            mntentfile = setmntent("/proc/mount", "r");
        }
        if (mntentfile == NULL) {
```

Comment (eplanet) [reply src/print_disk_info.c]: Well I wasn't sure file structure would be identically parsed between the two files. But if so, let's do that!

Thanks for the suggestion, but since there's a typo in the filename `/proc/mount` that should be `/proc/mounts`, I'm just adding it in the original commit if you don't mind.

**Comment by orestisf1993** [comment]
No problem, we would have squashed them anyway

**Comment by orestisf1993** [comment]
Thanks!
